site_name: mingw-w64
site_description: A complete runtime environment for GCC & LLVM for 32-bit (x86), 64-bit (x64), and ARM64 Windows
docs_dir: web/
theme:
    font: false
    logo: logo.svg
    name: material
    favicon: logo.svg
    palette:
      - media: "(prefers-color-scheme)"
        toggle:
          icon: material/brightness-auto
          name: Switch to light mode
      - scheme: default
        media: "(prefers-color-scheme: light)"
        toggle:
          icon: material/brightness-7
          name: Switch to dark mode
        primary: 'white'
        accent: 'indigo'
      - scheme: slate
        media: "(prefers-color-scheme: dark)"
        toggle:
          icon: material/brightness-4
          name: Switch to light mode
        primary: 'black'
        accent: 'indigo'
    features:
        - navigation.instant
        - content.action.edit
        - content.code.copy
        - content.tabs.link
    custom_dir: overrides

extra_css:
    - 'stylesheets/extra.css'
    - 'stylesheets/fonts.css'

site_url: https://www.mingw-w64.org
repo_url: https://github.com/mingw-w64/mingw-w64.github.io
edit_uri: edit/source/web/

markdown_extensions:
    - meta
    - attr_list
    - codehilite
    - sane_lists
    - admonition
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde
    - pymdownx.tabbed:
        alternate_style: true

nav:
  - 'Introduction': index.md
  - changelog.md
  - Downloads:
    - downloads.md
    - source.md
  - Getting Started:
    - getting-started/archlinux.md
    - getting-started/debian.md
    - getting-started/fedora.md
    - getting-started/msys2.md
    - getting-started/msys2-llvm.md
  - Build Systems:
    - build-systems/meson.md
    - build-systems/cmake.md
  - Tools:
    - gendef: tools/gendef.md
    - genidl: tools/genidl.md
    - genpeimg: tools/genpeimg.md
    - widl: tools/widl.md
  - support.md
  - Old Pages:
    - contribute.md
    - donate.md